# Generated by Django 5.2.17 on 2026-09-22 20:52

import collector.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('read', 'Read aloud'), ('elicited', 'Own words')], max_length=8)),
                ('language', models.CharField(choices=[('pidgin', 'Pidgin'), ('english', 'English')], max_length=8)),
                ('intent', models.CharField(choices=[('transfer', 'Transfer'), ('balance', 'Balance'), ('airtime', 'Airtime'), ('bill', 'Bill payment'), ('history', 'History'), ('confirm', 'Confirm'), ('cancel', 'Cancel')], max_length=10)),
                ('template_id', models.CharField(max_length=20)),
                ('display_text', models.TextField()),
                ('transcript', models.TextField(blank=True)),
                ('entities', models.JSONField(default=dict)),
                ('recording_count', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['active', 'language', 'mode', 'recording_count'], name='collector_p_active_8c9076_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('mode', 'read')), fields=('transcript',), name='uniq_read_prompt_transcript')],
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(default=collector.models.new_speaker_code, max_length=8, unique=True)),
                ('consent_version', models.CharField(max_length=10)),
                ('consented_at', models.DateTimeField()),
                ('age_band', models.CharField(choices=[('18-24', '18–24'), ('25-34', '25–34'), ('35-44', '35–44'), ('45-54', '45–54'), ('55+', '55 and over')], max_length=8)),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('undisclosed', 'Prefer not to say')], max_length=12)),
                ('first_language', models.CharField(choices=[('yoruba', 'Yoruba'), ('igbo', 'Igbo'), ('hausa', 'Hausa'), ('pidgin', 'Nigerian Pidgin'), ('english', 'English'), ('other', 'Other')], max_length=10)),
                ('first_language_other', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(choices=[('Abia', 'Abia'), ('Adamawa', 'Adamawa'), ('Akwa Ibom', 'Akwa Ibom'), ('Anambra', 'Anambra'), ('Bauchi', 'Bauchi'), ('Bayelsa', 'Bayelsa'), ('Benue', 'Benue'), ('Borno', 'Borno'), ('Cross River', 'Cross River'), ('Delta', 'Delta'), ('Ebonyi', 'Ebonyi'), ('Edo', 'Edo'), ('Ekiti', 'Ekiti'), ('Enugu', 'Enugu'), ('Federal Capital Territory', 'Federal Capital Territory'), ('Gombe', 'Gombe'), ('Imo', 'Imo'), ('Jigawa', 'Jigawa'), ('Kaduna', 'Kaduna'), ('Kano', 'Kano'), ('Katsina', 'Katsina'), ('Kebbi', 'Kebbi'), ('Kogi', 'Kogi'), ('Kwara', 'Kwara'), ('Lagos', 'Lagos'), ('Nasarawa', 'Nasarawa'), ('Niger', 'Niger'), ('Ogun', 'Ogun'), ('Ondo', 'Ondo'), ('Osun', 'Osun'), ('Oyo', 'Oyo'), ('Plateau', 'Plateau'), ('Rivers', 'Rivers'), ('Sokoto', 'Sokoto'), ('Taraba', 'Taraba'), ('Yobe', 'Yobe'), ('Zamfara', 'Zamfara'), ('outside', 'Outside Nigeria')], max_length=30, verbose_name='state you grew up in')),
                ('language_pref', models.CharField(choices=[('pidgin', 'Mostly Pidgin'), ('english', 'Mostly English'), ('both', 'Both equally')], max_length=8)),
                ('environment', models.CharField(choices=[('quiet', 'Quiet room'), ('some', 'Some background noise'), ('noisy', 'Noisy (street, market, bus)')], max_length=8)),
                ('user_agent', models.TextField(blank=True)),
                ('withdrawn', models.BooleanField(default=False)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['withdrawn', 'created_at'], name='collector_s_withdra_38f24f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audio', models.FileField(max_length=200, upload_to=collector.models.audio_upload_path)),
                ('mime_type', models.CharField(max_length=60)),
                ('duration_ms', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('peak_level', models.FloatField(help_text='0–1, from the browser analyser', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('clip_fraction', models.FloatField(default=0.0, help_text='share of analyser frames at full scale; high means distorted', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('transcript_override', models.TextField(blank=True, help_text='Verbatim transcript for elicited prompts, or a correction if the speaker deviated.')),
                ('review_note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recordings', to='collector.prompt')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='collector.speaker')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='collector_r_status_ae1001_idx'), models.Index(fields=['speaker', 'prompt'], name='collector_r_speaker_91fa1e_idx')],
                'constraints': [models.UniqueConstraint(fields=('speaker', 'prompt'), name='uniq_speaker_prompt')],
            },
        ),
    ]
