# Generated by Django 5.2.17 on 2026-09-21 20:55

import collector.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(default=collector.models.new_speaker_code, max_length=8, unique=True)),
                ('consent_version', models.CharField(max_length=10)),
                ('consented_at', models.DateTimeField()),
                ('age_band', models.CharField(choices=[('18-24', '18–24'), ('25-34', '25–34'), ('35-44', '35–44'), ('45-54', '45–54'), ('55+', '55 and over')], max_length=8)),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('undisclosed', 'Prefer not to say')], max_length=12)),
                ('first_language', models.CharField(choices=[('yoruba', 'Yoruba'), ('igbo', 'Igbo'), ('hausa', 'Hausa'), ('pidgin', 'Nigerian Pidgin'), ('english', 'English'), ('other', 'Other')], max_length=10)),
                ('first_language_other', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(max_length=40, verbose_name='state you grew up in')),
                ('language_pref', models.CharField(choices=[('pidgin', 'Mostly Pidgin'), ('english', 'Mostly English'), ('both', 'Both equally')], max_length=8)),
                ('environment', models.CharField(choices=[('quiet', 'Quiet room'), ('some', 'Some background noise'), ('noisy', 'Noisy (street, market, bus)')], max_length=8)),
                ('user_agent', models.TextField(blank=True)),
                ('withdrawn', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('read', 'Read aloud'), ('elicited', 'Own words')], max_length=8)),
                ('language', models.CharField(choices=[('pidgin', 'Pidgin'), ('english', 'English')], max_length=8)),
                ('intent', models.CharField(choices=[('transfer', 'Transfer'), ('balance', 'Balance'), ('airtime', 'Airtime'), ('bill', 'Bill payment'), ('history', 'History'), ('confirm', 'Confirm'), ('cancel', 'Cancel')], max_length=10)),
                ('template_id', models.CharField(max_length=20)),
                ('display_text', models.TextField()),
                ('transcript', models.TextField(blank=True)),
                ('entities', models.JSONField(default=dict)),
                ('recording_count', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['mode', 'language', 'recording_count'], name='collector_p_mode_e27995_idx')],
            },
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audio', models.FileField(upload_to=collector.models.audio_upload_path)),
                ('mime_type', models.CharField(max_length=60)),
                ('duration_ms', models.PositiveIntegerField()),
                ('peak_level', models.FloatField(help_text='0–1, from the browser analyser')),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('transcript_override', models.TextField(blank=True, help_text='Verbatim transcript for elicited prompts, or a correction if the speaker deviated.')),
                ('review_note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recordings', to='collector.prompt')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='collector.speaker')),
            ],
        ),
    ]
